import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
const dir=new URL('../migrations/',import.meta.url),sql=readFileSync(new URL('0024_financial_optimization.sql',dir),'utf8');
function oldSchema(){const raw=new DatabaseSync(':memory:');raw.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(dir).filter(f=>f.endsWith('.sql')&&f<'0024').sort()){raw.exec('BEGIN');raw.exec(readFileSync(new URL(f,dir),'utf8'));raw.exec('COMMIT');}
 raw.exec(`INSERT INTO customers(id,telegram_user_id,balance_irt) VALUES(1,'101',100),(2,'102',0);UPDATE customers SET referred_by=1 WHERE id=2;
 INSERT INTO orders(id,customer_id,state,selections,amount,panel_id,pasarguard_user_id,pasarguard_username,idempotency_key,payment_reference,receipt_file_id) VALUES('old-order',1,'completed','{}',100,'legacy','101','old-user','old-token','payment-preserved','receipt-preserved');
 INSERT INTO wallet_entries(id,customer_id,delta_irt,kind,order_id,actor,balance_after) VALUES('old-payment',1,-10,'order_payment','old-order','customer',100),('old-topup-entry',1,45000,'topup_credit','old-topup','admin:9',100);
 INSERT INTO wallet_topups(id,customer_id,amount_irt,state,idempotency_key) VALUES('old-topup',1,45000,'approved','old-topup-token'),('old-approved-no-ledger',1,45000,'approved','another-token'),('pending',1,45000,'pending_review','pending-token');
 INSERT INTO referral_rewards(referred_customer_id,referrer_customer_id,order_id,amount_irt) VALUES(2,1,'old-order',10);
 INSERT INTO order_events(order_id,actor,action,data) VALUES('old-order','system','history_kept','{"usage":123}');
 INSERT INTO announcements(id,body,created_by,state,started_at,total_estimate,audience_highwater,audience_seeded) VALUES('old-ann','preserved','admin:9','sending','2026-01-01',2,2,1);
 INSERT INTO announcement_deliveries(announcement_id,customer_id,status) VALUES('old-ann',1,'sent'),('old-ann',2,'pending');
 INSERT INTO panels(id,name,origin,credentials) VALUES('dest','destination','https://dest.example.com','encrypted-evidence');
 INSERT INTO service_migrations(id,service_id,customer_id,operator,source_panel_id,source_origin,source_user_id,source_username,destination_panel_id,destination_origin,destination_revision,destination_username,destination_config,state,confirmation_token,review_expires_at,entitlement,error) VALUES('pending-migration','old-order',1,'9','legacy','https://source.example.com','101','old-user','dest','https://dest.example.com',1,'destination-user','{}','creating','nonce',9999999999999,'{}','destination_creation_unverified');`);return raw;}
function snapshot(c:DatabaseSync){return Object.fromEntries(c.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(row=>{const name=String(row.name);return [name,{columns:c.prepare('PRAGMA table_info('+name+')').all().map(r=>String(r.name)),rows:c.prepare('SELECT * FROM '+name+' ORDER BY 1,2').all()}]}));}
test('0024 additive upgrade preserves all29tables, original columns, financial and announcement evidence',()=>{const raw=oldSchema();try{const before=snapshot(raw);assert.equal(Object.keys(before).length,29);raw.exec('BEGIN');raw.exec(sql);raw.exec('COMMIT');for(const [t,v]of Object.entries(before))assert.deepEqual(raw.prepare('SELECT '+v.columns.map(x=>'"'+x+'"').join(',')+' FROM '+t+' ORDER BY 1,2').all(),v.rows,t);assert.equal(Object.keys(snapshot(raw)).length,29);assert.deepEqual(raw.prepare('PRAGMA foreign_key_check').all(),[]);assert.equal(raw.prepare("SELECT credit_status FROM wallet_topups WHERE id='old-topup'").get()!.credit_status,'review_required');assert.equal(raw.prepare("SELECT credit_status FROM wallet_topups WHERE id='old-approved-no-ledger'").get()!.credit_status,'review_required');assert.equal(raw.prepare("SELECT credit_status FROM wallet_topups WHERE id='pending'").get()!.credit_status,'uncredited');assert.equal(raw.prepare('SELECT ledger_id FROM referral_rewards').get()!.ledger_id,null);assert.equal(raw.prepare('SELECT next_recovery_at FROM service_migrations').get()!.next_recovery_at,0);}finally{raw.close();}});
test('0024 interrupted transaction rollback and raw repeat failure preserve the complete tree of records',()=>{const raw=oldSchema();try{const before=snapshot(raw);raw.exec('BEGIN');raw.exec(sql);raw.exec('ROLLBACK');assert.deepEqual(snapshot(raw),before);raw.exec('BEGIN');raw.exec(sql);raw.exec('COMMIT');const after=snapshot(raw);raw.exec('BEGIN');assert.throws(()=>raw.exec(sql),/duplicate column/);raw.exec('ROLLBACK');assert.deepEqual(snapshot(raw),after);assert.deepEqual(raw.prepare('PRAGMA foreign_key_check').all(),[]);}finally{raw.close();}});
test('0024 fresh installation retains schema29 and financial identity constraints',()=>{const raw=new DatabaseSync(':memory:');try{raw.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(dir).filter(f=>f.endsWith('.sql')).sort()){raw.exec('BEGIN');raw.exec(readFileSync(new URL(f,dir),'utf8'));raw.exec('COMMIT');}assert.equal(Object.keys(snapshot(raw)).length,29);assert.deepEqual(raw.prepare('PRAGMA foreign_key_check').all(),[]);for(const name of ['idx_wallet_operation_key','idx_wallet_refund_lookup','idx_wallet_recovery_due','idx_migration_recovery_due'])assert.ok(raw.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name=?").get(name));}finally{raw.close();}});
