/** Real local workerd/D1, real authenticated endpoints, isolated read-only upstream. */
import {test} from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {freshDb,ADMIN} from './helpers.ts';
const require=createRequire(import.meta.url);
test('workerd selected status verification is authenticated, bounded and persisted only by fresh save',async()=>{
 const {build}=require('esbuild'),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),WEB='https://runtime-bot.example.com',BOT='SYNTHETIC-RUNTIME-BOT',KEY='SYNTHETIC-RUNTIME-GROUP-KEY';
 const built=await build({stdin:{contents:`import {syncConfiguredPanels} from './src/panels/bindings.ts';import {panelCallback,panelAdminRoute,testPanel} from './src/panels/admin.ts';import {uiFor} from './src/telegram/i18n.ts';export default{async fetch(req,env){const p=new URL(req.url).pathname;if(p==='/fixture/test'||p==='/fixture/edit'){await syncConfiguredPanels(env);const sent=[];const ctx={env,db:env.DB,actor:{id:${ADMIN.id}},chatId:${ADMIN.id},customerId:1,isAdmin:true,ui:uiFor('en'),api:{sendMessage:async(chat,text,kb)=>sent.push({text,kb}),answerCallbackQuery:async()=>{}}};await panelCallback(ctx,p.endsWith('/test')?'pnl:test:cf_1':'pnl:edit:cf_1','fixture');return Response.json({sent,test:await testPanel(env,'cf_1')});}return panelAdminRoute(req,env);}};`,resolveDir:process.cwd(),sourcefile:'group-workflow-runtime.ts'},bundle:true,format:'esm',platform:'browser',target:'es2022',write:false});
 const calls:{host:string;path:string;method:string}[]=[];const mf=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],script:built.outputFiles[0].text,d1Databases:{DB:'groups-runtime-local'},bindings:{TELEGRAM_BOT_TOKEN:BOT,ADMIN_CHAT_ID:String(ADMIN.id),PANEL_ADMIN_ORIGIN:WEB,PANEL_COUNT:'1',PANEL_1_URL:'https://panel.mrapanel.shop:8000',PANEL_1_NAME:'MraPanel',PANEL_1_API_KEY:KEY,PASARGUARD_PANEL_URL:'https://legacy.example.com'},outboundService:async(request:Request)=>{const u=new URL(request.url);assert.equal(request.method,'GET');if(u.origin==='https://cloudflare-dns.com'){assert.equal(request.headers.get('x-api-key'),null);return Response.json(u.searchParams.get('type')==='A'?{Status:0,Answer:[{type:1,data:'176.120.17.222'}]}:{Status:0});}assert.equal(u.origin,'https://panel.mrapanel.shop:8000');assert.equal(request.headers.get('x-api-key'),KEY);calls.push({host:u.origin,path:u.pathname+u.search,method:request.method});if(u.pathname==='/api/admin')return Response.json({username:'operator',status:'active',role:{is_owner:true}});if(u.pathname==='/api/groups')return Response.json({detail:'Permission denied'},{status:403});if(u.pathname==='/api/groups/simple')return Response.json({groups:[{id:17,name:'Actual group'}],total:1});if(u.pathname==='/api/group/17')return Response.json({id:17,name:'Actual group',is_disabled:false});throw Error('Unexpected path');}}));
 try{const db=await mf.getD1Database('DB'),raw=freshDb();try{for(const name of ['panels','panel_audit','panel_selection','panel_admin_sessions']){const schema=raw.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(name)!.sql;await db.prepare(String(schema)).run();}}finally{raw.close();}await db.prepare("INSERT INTO panels(id,name,enabled_new) VALUES('legacy','Legacy',1)").run();await db.prepare("INSERT INTO panel_selection(singleton,panel_id) VALUES(1,'legacy')").run();
 const sign=async(key:Uint8Array,text:string)=>new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']),new TextEncoder().encode(text)));const auth=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id:ADMIN.id})}),key=await sign(new TextEncoder().encode('WebAppData'),BOT);auth.set('hash',[...await sign(key,[...auth.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n'))].map(n=>n.toString(16).padStart(2,'0')).join(''));const initData=auth.toString();
 const first=await(await mf.dispatchFetch(WEB+'/fixture/test')).json() as any;assert.equal(first.test,'groups_status_unverified');const url=first.sent.flatMap(m=>m.kb?.inline_keyboard??[]).flat().find(b=>b.web_app).web_app.url;const token=new URL(url).searchParams.get('nonce');
 const post=(path:string,nonce:string,extra:any={})=>mf.dispatchFetch(WEB+'/admin/panels/'+path,{method:'POST',headers:{origin:WEB,'content-type':'application/json'},body:JSON.stringify({nonce,initData,...extra})});let res=await post('groups',token,{url:'https://panel.mrapanel.shop:8000',apiKey:''});assert.equal(res.status,200);assert.deepEqual(await res.json(),{groups:[{id:17,name:'Actual group',statusVerified:false}]});res=await post('groups',token,{url:'https://panel.mrapanel.shop:8000',apiKey:'',verifyIds:[17]});assert.equal(res.status,200);assert.deepEqual(await res.json(),{statuses:[{id:17,disabled:false}]});assert.equal((await db.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").first()).group_ids,'[]');res=await post('configure',token,{name:'MraPanel',url:'https://panel.mrapanel.shop:8000',apiKey:'',groups:[17]});assert.equal(res.status,200);assert.equal((await db.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").first()).group_ids,'[17]');
 const reopened=await(await mf.dispatchFetch(WEB+'/fixture/edit')).json() as any;assert.equal(reopened.test,'ok');const editUrl=reopened.sent.flatMap(m=>m.kb?.inline_keyboard??[]).flat().find(b=>b.web_app).web_app.url;res=await post('metadata',new URL(editUrl).searchParams.get('nonce')!);const metadata=await res.json();assert.deepEqual(metadata.groups,[17]);assert.equal(metadata.managed,true);assert.ok(!JSON.stringify(metadata).includes(KEY));assert.equal((await db.prepare('SELECT panel_id FROM panel_selection').first()).panel_id,'legacy');assert.ok(calls.every(c=>c.method==='GET'&&c.host==='https://panel.mrapanel.shop:8000'));
 }finally{await mf.dispose();}
});
