/** Actual managed-panel handlers/form with upstream 5.4.1 wire fixtures; offline only. */
import {test,beforeEach,afterEach} from 'node:test';import assert from 'node:assert/strict';import {runInNewContext} from 'node:vm';
import {freshDb,makeD1Shim,ADMIN,USER} from './helpers.ts';import {panelFormDom} from './panelFormDom.ts';import {syncConfiguredPanels} from '../src/panels/bindings.ts';import {testPanel,panelCallback,panelAdminRoute} from '../src/panels/admin.ts';import {resolvePanel,selection,provisioningForPanel} from '../src/panels/registry.ts';import {uiFor} from '../src/telegram/i18n.ts';import type {Env,UpdateContext} from '../src/types.ts';
const ORIGIN='https://panel.mrapanel.shop:8000',OTHER='https://other-groups.example.com',WEB='https://bot-groups.example.com',KEY='SYNTHETIC-MRA-GROUP-KEY',OTHERKEY='SYNTHETIC-OTHER-GROUP-KEY';
let raw:ReturnType<typeof freshDb>,env:Env,ctx:UpdateContext,real:typeof fetch,messages:{text:string;kb:any}[],calls:{origin:string;path:string;method:string}[];
let failStage:string,failStatus:number,malformed:boolean,groups:{id:number;name:string;is_disabled?:unknown}[],otherGroups:{id:number;name:string;is_disabled?:unknown}[],badGroup:unknown;
function set(k:string,v:unknown){(env as unknown as Record<string,unknown>)[k]=v;}
beforeEach(async()=>{raw=freshDb();const db=makeD1Shim(raw) as unknown as D1Database;env={DB:db,TELEGRAM_BOT_TOKEN:'SYNTHETIC-BOT-TOKEN',TELEGRAM_WEBHOOK_SECRET:'SYNTHETIC-WEBHOOK',ADMIN_CHAT_ID:String(ADMIN.id),PANEL_ADMIN_ORIGIN:WEB,PANEL_ENCRYPTION_KEY:btoa('g'.repeat(32)),PASARGUARD_PANEL_URL:'https://legacy.example.com',PASARGUARD_API_KEY:'SYNTHETIC-LEGACY',PANEL_COUNT:'1'};
 set('PANEL_1_NAME','MraPanel');set('PANEL_1_URL','https://panel.MraPanel.shop:8000');set('PANEL_1_API_KEY',KEY);groups=[{id:17,name:'Mra group one',is_disabled:false},{id:18,name:'گروه دوم',is_disabled:false}];otherGroups=[{id:23,name:'Other group',is_disabled:false}];messages=[];calls=[];failStage='';failStatus=0;malformed=false;badGroup=undefined;real=fetch;
 const api={sendMessage:async(_chat:number,text:string,kb:any)=>{messages.push({text,kb});},answerCallbackQuery:async()=>{},editMessageText:async()=>{}};ctx={env,db,api,actor:{id:ADMIN.id},chatId:ADMIN.id,customerId:1,isAdmin:true,ui:uiFor('en')} as unknown as UpdateContext;
 globalThis.fetch=async(input,init)=>{const u=new URL(String(input));if(u.origin==='https://cloudflare-dns.com'){assert.equal(init?.redirect,'manual');assert.equal(new Headers(init?.headers).get('x-api-key'),null);return Response.json(u.searchParams.get('type')==='A'?{Status:0,Answer:[{type:1,data:'176.120.17.222'}]}:{Status:0});}
  assert.ok([ORIGIN,OTHER].includes(u.origin),'no implicit other panel');assert.equal(new Headers(init?.headers).get('x-api-key'),u.origin===ORIGIN?KEY:OTHERKEY);assert.equal(new Headers(init?.headers).get('authorization'),null);assert.equal(init?.redirect,'manual');assert.equal(init?.method??'GET','GET','configuration test never creates/updates remote users');calls.push({origin:u.origin,path:u.pathname+u.search,method:init?.method??'GET'});
  const stage=u.pathname==='/api/admin'?'admin':(u.pathname==='/api/groups'||u.pathname==='/api/groups/simple')?'list':'group';if(stage===failStage)return Response.json({detail:KEY},{status:failStatus});
  if(stage==='admin')return Response.json({username:'operator',status:'active',role:{is_owner:true}});
  const source=u.origin===ORIGIN?groups:otherGroups;if(stage==='list'){if(malformed)return Response.json({groups:[{id:'17',name:KEY}],total:1});const offset=Number(u.searchParams.get('offset')),limit=Number(u.searchParams.get('limit'));assert.equal(limit,100);return Response.json({groups:source.slice(offset,offset+limit).map(g=>({...g,inbound_tags:['fixture-only'],total_users:0})),total:source.length});}
  if(badGroup!==undefined)return Response.json(badGroup);const found=source.find(g=>g.id===Number(u.pathname.split('/').at(-1)));return found?Response.json({...found,inbound_tags:[],total_users:0}):Response.json({detail:'Group not found'},{status:404});
 };await syncConfiguredPanels(env);
});afterEach(()=>{globalThis.fetch=real;raw.close();});
async function signed(actor=ADMIN.id){const p=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id:actor})});const sign=async(key:Uint8Array,text:string)=>new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']),new TextEncoder().encode(text)));const key=await sign(new TextEncoder().encode('WebAppData'),env.TELEGRAM_BOT_TOKEN),data=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n');p.set('hash',[...await sign(key,data)].map(n=>n.toString(16).padStart(2,'0')).join(''));return p.toString();}
function latestForm(){return messages.flatMap(m=>m.kb?.inline_keyboard??[]).flat().filter(b=>b.web_app).at(-1)?.web_app.url as string;}
async function open(id='cf_1'){await panelCallback(ctx,'pnl:edit:'+id,'test');return latestForm();}
async function post(url:string,action:string,extra:any={}){return panelAdminRoute(new Request(WEB+'/admin/panels/'+action,{method:'POST',headers:{origin:WEB,'content-type':'application/json'},body:JSON.stringify({nonce:new URL(url).searchParams.get('nonce'),initData:await signed(),...extra})}),env);}
async function browser(url:string){const html=await(await panelAdminRoute(new Request(url),env)).text(),script=/<script nonce="[^"]+">([\s\S]*?)<\/script>/.exec(html)![1]!,dom=panelFormDom(),initData=await signed();await runInNewContext(script,{document:dom.document,URL,setTimeout:dom.setTimeout,clearTimeout:dom.clearTimeout,window:{Telegram:{WebApp:{initData,ready:()=>{}}}},fetch:async(path:string,init:RequestInit)=>panelAdminRoute(new Request(WEB+path,{...init,headers:{origin:WEB,'content-type':'application/json'}}),env)});return {...dom,html};}
async function save(url:string,ids:number[],id='cf_1'){const p=raw.prepare('SELECT origin FROM panels WHERE id=?').get(id)!;return post(url,'configure',{name:id==='cf_1'?'MraPanel':'Other',url:p.origin,apiKey:'',groups:ids});}
test('missing GROUP_IDS seeds empty configuration; Test actually discovers and opens owner-bound selector',async()=>{assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[]');await panelCallback(ctx,'pnl:test:cf_1','test');assert.equal(raw.prepare("SELECT last_test FROM panels WHERE id='cf_1'").get()!.last_test,'groups_missing');assert.ok(calls.some(c=>c.path==='/api/groups?offset=0&limit=100'));const url=latestForm();assert.ok(url);assert.ok(messages.at(-1)!.text.includes('Group discovery succeeded'));const token=new URL(url).searchParams.get('nonce')!;const session=raw.prepare('SELECT * FROM panel_admin_sessions WHERE nonce=?').get(token)!;assert.equal(session.actor,String(ADMIN.id));assert.equal(session.panel_id,'cf_1');assert.equal(session.action,'configure');assert.equal((await selection(env.DB)).panel_id,'legacy');});
test('direct Test selector saves numeric IDs and reopens with persisted selections without any environment GROUP_IDS',async()=>{await panelCallback(ctx,'pnl:test:cf_1','test');let url=latestForm(),b=await browser(url);assert.deepEqual(b.names(),['Mra group one','گروه دوم']);assert.equal(b.get('key-row').hidden,true);assert.equal(b.get('key').value,'');assert.equal(b.get('url').disabled,true);assert.equal(b.get('save').disabled,true);b.checkboxes()[1].checked=true;b.checkboxes()[1].onchange();assert.equal(b.get('group-count').textContent,'1 group selected');await b.get('f').onsubmit({preventDefault(){}});assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[18]');assert.equal(b.get('status').textContent,ctx.ui.t.panelFormManagedSaved);assert.equal((await save(url,[17])).status,403,'save nonce stays one-use');await syncConfiguredPanels(env);url=await open();b=await browser(url);assert.deepEqual(b.checkboxes().map(c=>[Number(c.value),c.checked]),[[17,false],[18,true]]);assert.equal(await testPanel(env,'cf_1'),'ok');const row=raw.prepare("SELECT * FROM panels WHERE id='cf_1'").get()!;assert.equal(row.credentials,null);assert.equal(row.credential_binding,'PANEL_1_API_KEY');assert.ok(!JSON.stringify(row).includes(KEY));});
test('list pagination returns every actual group before selecting later-page IDs',async()=>{groups=Array.from({length:205},(_,n)=>({id:n+1,name:'Group '+(n+1),is_disabled:false}));const url=await open(),r=await post(url,'groups',{url:ORIGIN,apiKey:''});assert.equal(r.status,200);const body=await r.json() as any;assert.equal(body.groups.length,205);assert.deepEqual(calls.filter(c=>c.path.startsWith('/api/groups')).map(c=>c.path),['/api/groups?offset=0&limit=100','/api/groups?offset=100&limit=100','/api/groups?offset=200&limit=100']);assert.equal((await save(url,[205])).status,200);assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[205]');});
for(const status of [401,403,404,500])test('missing selections with group-list HTTP '+status+' report actual failure, not groups_missing',async()=>{failStage='list';failStatus=status;const result=await testPanel(env,'cf_1');assert.equal(result,{401:'group_discovery_auth_401',403:'group_discovery_permission_403',404:'group_discovery_not_found_404',500:'group_discovery_server_500'}[status]);await panelCallback(ctx,'pnl:test:cf_1','test');assert.ok(!messages.at(-1)!.text.includes(KEY));assert.equal(latestForm(),undefined);assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[]');});
for(const status of [401,403])test('admin HTTP '+status+' is distinguished before any group call',async()=>{failStage='admin';failStatus=status;assert.equal(await testPanel(env,'cf_1'),status===401?'test_auth_401':'test_permission_403');assert.ok(!calls.some(c=>c.path.startsWith('/api/group')));});
test('malformed group list is an upstream parse failure, not missing local selections',async()=>{malformed=true;assert.equal(await testPanel(env,'cf_1'),'group_discovery_parse_200');const url=await open(),r=await post(url,'groups',{url:ORIGIN,apiKey:''});assert.equal(r.status,502);assert.deepEqual(await r.json(),{code:'discovery_failed'});});
test('empty and all-disabled API lists are different from a valid unselected list',async()=>{groups=[];assert.equal(await testPanel(env,'cf_1'),'groups_none_available');groups=[{id:17,name:'Disabled',is_disabled:true}];assert.equal(await testPanel(env,'cf_1'),'groups_none_enabled');const b=await browser(await open());assert.equal(b.get('save').disabled,true);assert.equal(b.get('group-state').textContent,ctx.ui.t.panelGroupsNoneEnabled);});
test('disabled groups cannot be selected or included by Select All; existing disabled IDs are warned',async()=>{groups[1]!.is_disabled=true;raw.exec("UPDATE panels SET group_ids='[18]' WHERE id='cf_1'");const b=await browser(await open());assert.equal(b.checkboxes()[1].disabled,true);assert.equal(b.checkboxes()[1].checked,false);assert.equal(b.get('group-warning').hidden,false);b.get('select-all').checked=true;b.get('select-all').onchange();assert.deepEqual(b.checkboxes().map(c=>c.checked),[true,false]);assert.equal(b.get('group-count').textContent,'1 group selected');await b.get('f').onsubmit({preventDefault(){}});assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[17]');});
for(const status of [401,403,404,500])test('selected-group HTTP '+status+' is accurately classified and failed save keeps old IDs',async()=>{raw.exec("UPDATE panels SET group_ids='[17]' WHERE id='cf_1'");failStage='group';failStatus=status;assert.equal(await testPanel(env,'cf_1'),{401:'group_read_auth_401',403:'group_read_permission_403',404:'group_read_not_found_404',500:'group_read_server_500'}[status]);const url=await open(),r=await save(url,[18]);assert.equal(r.status,422);const body=await r.json() as any;assert.equal(body.code,{401:'key_rejected',403:'group_details_permission_denied',404:'group_not_found',500:'configuration_test_failed'}[status]);assert.ok(!JSON.stringify(body).includes(KEY));assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[17]');});
for(const response of [{id:'17',is_disabled:false},{id:999,is_disabled:false},{id:17},{id:17,is_disabled:'false'}])test('unexpected selected-group response cannot pass '+JSON.stringify(response),async()=>{raw.exec("UPDATE panels SET group_ids='[17]' WHERE id='cf_1'");badGroup=response;assert.equal(await testPanel(env,'cf_1'),'group_response_unexpected_17');assert.equal((await save(await open(),[17])).status,422);});
test('selected disabled group gives specific test/save error and never erases prior selection',async()=>{raw.exec("UPDATE panels SET group_ids='[17]' WHERE id='cf_1'");groups[0]!.is_disabled=true;assert.equal(await testPanel(env,'cf_1'),'group_disabled_17');const r=await save(await open(),[17]);assert.equal((await r.json() as any).code,'group_disabled');assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[17]');});
for(const input of ['["17"]','{}','[17,17]','[0]'])test('invalid saved group configuration fails explicitly '+input,async()=>{raw.prepare("UPDATE panels SET group_ids=? WHERE id='cf_1'").run(input);assert.equal(await testPanel(env,'cf_1'),'groups_invalid_configuration');assert.equal(calls.length,0);});
test('synchronization and credential rotation never overwrite saved Mini App groups',async()=>{assert.equal((await save(await open(),[18])).status,200);const before=raw.prepare("SELECT revision,group_ids FROM panels WHERE id='cf_1'").get()!;for(const v of [undefined,'[]','malformed','[999]']){set('PANEL_1_GROUP_IDS',v);await syncConfiguredPanels(env);assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[18]');assert.equal(raw.prepare("SELECT revision FROM panels WHERE id='cf_1'").get()!.revision,before.revision);}const oldResolved=await resolvePanel(env,'cf_1');assert.equal(oldResolved.ok,true);set('PANEL_1_API_KEY','SYNTHETIC-ROTATED-GROUP-KEY');await syncConfiguredPanels(env);assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[18]');assert.equal(raw.prepare("SELECT enabled_new FROM panels WHERE id='cf_1'").get()!.enabled_new,0);});
test('two managed panels retain independent selection, credentials, groups and explicit default confirmation',async()=>{set('PANEL_COUNT','2');set('PANEL_2_URL',OTHER);set('PANEL_2_NAME','Other');set('PANEL_2_API_KEY',OTHERKEY);await syncConfiguredPanels(env);assert.equal((await save(await open('cf_1'),[18])).status,200);assert.equal((await save(await open('cf_2'),[23],'cf_2')).status,200);await syncConfiguredPanels(env);for(const [id,expected] of [['cf_1',18],['cf_2',23]] as const){assert.equal(await testPanel(env,id),'ok');assert.equal(raw.prepare('SELECT group_ids FROM panels WHERE id=?').get(id)!.group_ids,JSON.stringify([expected]));}const p1=await resolvePanel(env,'cf_1'),p2=await resolvePanel(env,'cf_2');assert.ok(p1.ok&&p2.ok);assert.equal(p1.config.baseUrl,ORIGIN);assert.equal(p2.config.baseUrl,OTHER);assert.equal((await selection(env.DB)).panel_id,'legacy');raw.exec("UPDATE panels SET enabled_new=1 WHERE id='cf_2'");await panelCallback(ctx,'pnl:select:cf_2','test');const token=raw.prepare("SELECT nonce FROM panel_admin_sessions WHERE action='select'").get()!.nonce;await panelCallback(ctx,'pnl:confirm:'+token,'test');assert.equal((await selection(env.DB)).panel_id,'cf_2');assert.deepEqual(provisioningForPanel(p1.row,{} as any).groupIds,[18]);assert.deepEqual(provisioningForPanel(p2.row,{} as any).groupIds,[23]);assert.ok(calls.every(c=>c.method==='GET'));});
test('unauthorized, owner-substituted and unsigned discovery/save cannot retrieve groups or mutate config',async()=>{const url=await open();for(const initData of ['',await signed(USER.id)]){assert.equal((await post(url,'groups',{initData,url:ORIGIN,apiKey:''})).status,403);assert.equal((await post(url,'configure',{initData,name:'MraPanel',url:ORIGIN,apiKey:'',groups:[17]})).status,403);}const untrusted={...ctx,actor:{id:USER.id},chatId:USER.id};await panelCallback(untrusted,'pnl:test:cf_1','attack');assert.equal(calls.length,0);assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[]');});
for(const locale of ['fa','en'] as const)test('missing-group CTA, disabled-state and save-error localization '+locale,async()=>{ctx.ui=uiFor(locale);await panelCallback(ctx,'pnl:test:cf_1','test');assert.ok(messages.at(-1)!.text.includes(ctx.ui.t.panelTestGroupsMissing));const b=await browser(latestForm());assert.ok(b.html.includes('dir="'+(locale==='fa'?'rtl':'ltr')+'"'));b.checkboxes()[0].checked=true;b.checkboxes()[0].onchange();failStage='group';failStatus=403;await b.get('f').onsubmit({preventDefault(){}});assert.equal(b.get('status').textContent,ctx.ui.t.panelGroupsDetailsPermission);assert.equal(b.get('save').disabled,true);assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[]');});
test('malformed disabled flag in discovered groups is never coerced into an enabled selection',async()=>{groups[0]!.is_disabled='false';assert.equal(await testPanel(env,'cf_1'),'group_discovery_parse_200');const r=await post(await open(),'groups',{url:ORIGIN,apiKey:''});assert.equal(r.status,502);assert.equal(raw.prepare("SELECT group_ids FROM panels WHERE id='cf_1'").get()!.group_ids,'[]');});
test('changing managed URL or using another panel URL in discovery never forwards the stored key',async()=>{set('PANEL_COUNT','2');set('PANEL_2_URL',OTHER);set('PANEL_2_API_KEY',OTHERKEY);await syncConfiguredPanels(env);const r=await post(await open(),'groups',{url:OTHER,apiKey:''});assert.equal(r.status,409);assert.equal(calls.length,0);assert.equal((await selection(env.DB)).panel_id,'legacy');});
