/** No live panel requests or credentials: DNS and API transport security regressions. */
import {test,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {publicDestination,publicAddress} from '../src/panels/security.ts';
import {PasarGuardClient} from '../src/pasarguard/client.ts';
const ORIGIN='https://panel.mrapanel.shop:8000',KEY='SYNTHETIC-DNS-REGRESSION-KEY';
let real:typeof fetch,a:unknown,aaaa:unknown,dnsFailure:string|null,redirect:number,calls:{host:string;type:string|null;key:string|null}[];
beforeEach(()=>{real=fetch;a={Status:0,Answer:[{name:'panel.mrapanel.shop',type:1,data:'176.120.17.222'}]};aaaa={Status:0,Authority:[{type:6,data:'synthetic SOA'}]};dnsFailure=null;redirect=0;calls=[];globalThis.fetch=async(input,init)=>{const u=new URL(String(input));assert.equal(init?.redirect,'manual');assert.ok(init?.signal);const key=new Headers(init?.headers).get('x-api-key');calls.push({host:u.origin,type:u.searchParams.get('type'),key});
 if(u.origin==='https://cloudflare-dns.com'){assert.equal(key,null);assert.equal(new Headers(init?.headers).get('accept'),'application/dns-json');assert.equal(u.searchParams.get('name'),'panel.mrapanel.shop');if(dnsFailure===u.searchParams.get('type'))throw new TypeError('synthetic transport failure');return Response.json(u.searchParams.get('type')==='A'?a:aaaa);}
 assert.equal(u.origin,ORIGIN);assert.equal(key,KEY);if(redirect)return new Response(redirect===304?null:JSON.stringify({detail:KEY}),{status:redirect,headers:{location:'https://unintended.example.com/'+KEY,'content-type':'application/json'}});return Response.json({username:'operator',status:'active',role:{is_owner:true}});
};});afterEach(()=>{globalThis.fetch=real;});
function client(){return new PasarGuardClient({baseUrl:ORIGIN,apiKey:KEY,panelId:'cf_1',validateDestination:()=>publicDestination(ORIGIN)});}
for(const variant of ['absent','empty','SOA'])test('public MraPanel A with normal AAAA '+variant+' succeeds',async()=>{aaaa=variant==='absent'?{Status:0}:variant==='empty'?{Status:0,Answer:[]}:{Status:0,Authority:[{type:6,data:'synthetic SOA'}]};assert.equal(await publicDestination(ORIGIN),true);const r=await client().getCurrentAdmin();assert.equal(r.ok,true);assert.equal(calls.filter(c=>c.key!==null).length,1);assert.equal(calls.at(-1)!.host,ORIGIN);});
test('public A plus globally routable AAAA succeeds',async()=>{aaaa={Status:0,Answer:[{type:28,data:'2606:4700:4700::1111'}]};assert.equal(await publicDestination(ORIGIN),true);});
test('public IPv6-only DNS succeeds with empty A, but no addresses on either family fails',async()=>{a={Status:0};aaaa={Status:0,Answer:[{type:28,data:'2606:4700:4700::1111'}]};assert.equal(await publicDestination(ORIGIN),true);aaaa={Status:0};assert.equal(await publicDestination(ORIGIN),false);});
for(const family of ['A','AAAA'])test(family+' transport failure fails closed even if other family is public',async()=>{dnsFailure=family;const r=await client().getCurrentAdmin();assert.equal(r.ok,false);if(!r.ok){assert.equal(r.kind,'bad_url');assert.equal(r.detail,'destination_not_public');}assert.equal(calls.filter(c=>c.key!==null).length,0);});
for(const status of [2,3,5])test('DNS Status '+status+' is not treated as valid no-AAAA data',async()=>{aaaa={Status:status};assert.equal(await publicDestination(ORIGIN),false);});
for(const addr of ['0.0.0.0','10.0.0.1','127.0.0.1','169.254.169.254','172.16.0.1','192.168.1.1','100.64.0.1','192.0.0.1','192.0.2.1','192.88.99.1','198.18.0.1','198.51.100.1','203.0.113.1','224.0.0.1','255.255.255.255','999.1.1.1','0176.120.17.222','176.120.17','176.120.17.222 trailing','::1','fc00::1','fe80::1','ff02::1','::ffff:127.0.0.1','2001:db8::1','2001::1','2002:0808:0808::1','3fff::1','2000::1::2'])test('mixed DNS rejects non-public/malformed '+addr+' before any key is sent',async()=>{assert.equal(publicAddress(addr),false);aaaa={Status:0,Answer:[{type:addr.includes(':')?28:1,data:addr}]};const r=await client().getCurrentAdmin();assert.equal(r.ok,false);assert.equal(calls.filter(c=>c.key!==null).length,0);});
for(const data of [null,[],false,'invalid',{Status:'0'},{Status:0,Answer:null},{Status:0,Answer:{}},{Status:0,Answer:[null]},{Status:0,Answer:[{type:1,data:12}]},{Status:0,Answer:[{type:'1',data:'8.8.8.8'}]},{Status:0,Answer:[{type:1,data:''}]},{Status:0,Answer:[{type:28,data:'176.120.17.222'}]},{Status:0,Answer:[{type:1,data:'2606:4700:4700::1111'}]},{Status:0,TC:true,Answer:[{type:1,data:'8.8.8.8'}]},{Status:0,TC:'false'},{Status:0,Answer:Array.from({length:65},()=>({type:1,data:'8.8.8.8'}))}])test('malformed or incomplete DNS payload rejected '+JSON.stringify(data).slice(0,65),async()=>{aaaa=data;assert.equal(await publicDestination(ORIGIN),false);});
test('CNAME chain with valid public terminal A is accepted; CNAME-only response is insufficient',async()=>{a={Status:0,Answer:[{type:5,data:'canonical.example.com'},{type:1,data:'176.120.17.222'}]};assert.equal(await publicDestination(ORIGIN),true);a={Status:0,Answer:[{type:5,data:'canonical.example.com'}]};assert.equal(await publicDestination(ORIGIN),false);});
for(const status of [301,302,303,304,307,308,403,429,503])test('DNS HTTP '+status+' never follows redirects or sends a panel key',async()=>{globalThis.fetch=async(_input,init)=>{assert.equal(init?.redirect,'manual');assert.equal(new Headers(init?.headers).get('x-api-key'),null);return new Response(null,{status,headers:{location:'https://unintended.example.com'}});};assert.equal(await publicDestination(ORIGIN),false);});
for(const status of [301,302,303,304,305,307,308])test('panel HTTP '+status+' is explicitly rejected without parsing reflected secrets or following Location',async()=>{redirect=status;const r=await client().getCurrentAdmin();assert.deepEqual(r,{ok:false,kind:'rejected',status,detail:'redirect_rejected'});assert.ok(!JSON.stringify(r).includes(KEY));assert.equal(calls.filter(c=>c.key!==null).length,1);assert.ok(calls.every(c=>[ORIGIN,'https://cloudflare-dns.com'].includes(c.host)));});
test('oversized and invalid JSON DNS body reject safely',async()=>{for(const text of ['not json',' '.repeat(32769)]){globalThis.fetch=async()=>new Response(text);assert.equal(await publicDestination(ORIGIN),false);}});
test('unsafe origins are rejected before performing any DNS or panel fetch',async()=>{for(const origin of ['http://panel.mrapanel.shop:8000','https://127.0.0.1:8000','https://panel.mrapanel.shop:444','https://u:p@panel.mrapanel.shop:8000','https://panel.mrapanel.shop:8000/dashboard'])assert.equal(await publicDestination(origin),false);assert.equal(calls.length,0);});

test('rejected DNS redirect bodies are cancelled without parsing',async()=>{let cancelled=0;globalThis.fetch=async()=>new Response(new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('untrusted'));},cancel(){cancelled++;}}),{status:302,headers:{location:'https://unintended.example.com'}});assert.equal(await publicDestination(ORIGIN),false);assert.equal(cancelled,2);});
test('rejected panel redirect body is cancelled without reading reflected secrets',async()=>{const dns=globalThis.fetch;let cancelled=false;globalThis.fetch=async(input,init)=>new URL(String(input)).origin==='https://cloudflare-dns.com'?dns(input,init):new Response(new ReadableStream({start(c){c.enqueue(new TextEncoder().encode(KEY));},cancel(){cancelled=true;}}),{status:302,headers:{location:'https://unintended.example.com'}});const result=await client().getCurrentAdmin();assert.deepEqual(result,{ok:false,kind:'rejected',status:302,detail:'redirect_rejected'});assert.equal(cancelled,true);});
