import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
const dir=new URL('../migrations/',import.meta.url),sql=readFileSync(new URL('0023_reliability_delivery.sql',dir),'utf8');
function baseline(){const c=new DatabaseSync(':memory:');c.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(dir).filter(f=>f.endsWith('.sql')&&f<'0023').sort()){c.exec('BEGIN');c.exec(readFileSync(new URL(f,dir),'utf8'));c.exec('COMMIT');}
 c.exec(`INSERT INTO customers(id,telegram_user_id,balance_irt) VALUES(1,'123',500),(2,'456',700);
 INSERT INTO orders(id,customer_id,state,selections,amount,idempotency_key,panel_id,pasarguard_user_id,pasarguard_username,receipt_file_id,payment_reference) VALUES('historical',1,'completed','{}',100,'historical-token','legacy','1','original','receipt','reference');
 INSERT INTO wallet_entries(id,customer_id,delta_irt,kind,order_id,actor,balance_after) VALUES('paid',1,-100,'order_payment','historical','customer',500),('reserved',2,-100,'order_payment','reserved-token','customer',700);
 INSERT INTO order_events(order_id,actor,action,data) VALUES('historical','system','usage_kept','{"usage":123}');
 INSERT INTO announcements(id,body,created_by,state,total_estimate,sent_count) VALUES('draft','draft','admin:456','sending',2,0),('started','started','admin:456','sending',2,1),('done','done','admin:456','done',1,1);
 INSERT INTO announcement_deliveries(announcement_id,customer_id,status,attempts) VALUES('started',1,'sent',1),('started',2,'sending',1),('done',1,'sent',1);`);return c;}
function snapshot(c:DatabaseSync){return Object.fromEntries(c.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(v=>{const n=String(v.name);return [n,{columns:c.prepare('PRAGMA table_info('+n+')').all().map(r=>String(r.name)),rows:c.prepare('SELECT * FROM '+n+' ORDER BY 1,2').all()}]}));}
test('0023 preserves all original columns/records and financial, customer, panel, migration relationships',()=>{const c=baseline(),before=snapshot(c);try{c.exec('BEGIN');c.exec(sql);c.exec('COMMIT');for(const [n,v]of Object.entries(before)){const cols=v.columns.map(n=>'"'+n+'"').join(',');assert.deepEqual(c.prepare('SELECT '+cols+' FROM '+n+' ORDER BY 1,2').all(),v.rows,n);}assert.deepEqual(c.prepare('PRAGMA foreign_key_check').all(),[]);assert.equal(c.prepare("SELECT payment_token FROM wallet_entries WHERE id='paid'").get()!.payment_token,'historical-token');assert.equal(c.prepare("SELECT payment_token FROM wallet_entries WHERE id='reserved'").get()!.payment_token,'reserved-token');assert.equal(c.prepare("SELECT started_at FROM announcements WHERE id='draft'").get()!.started_at,null);assert.ok(c.prepare("SELECT started_at FROM announcements WHERE id='started'").get()!.started_at);assert.equal(c.prepare("SELECT lease_until FROM announcement_deliveries WHERE announcement_id='started' AND customer_id=2").get()!.lease_until,0);}finally{c.close();}});
test('0023 transaction rollback and raw repeat failure preserve existing records',()=>{const c=baseline(),before=snapshot(c);try{c.exec('BEGIN');c.exec(sql);c.exec('ROLLBACK');assert.deepEqual(snapshot(c),before);c.exec('BEGIN');c.exec(sql);c.exec('COMMIT');const upgraded=snapshot(c);c.exec('BEGIN');assert.throws(()=>c.exec(sql));c.exec('ROLLBACK');assert.deepEqual(snapshot(c),upgraded);assert.deepEqual(c.prepare('PRAGMA foreign_key_check').all(),[]);}finally{c.close();}});
test('legacy-shaped wallet inserts receive stable tokens; funded order linking is guarded and atomic',()=>{const c=baseline();try{c.exec('BEGIN');c.exec(sql);c.exec('COMMIT');c.exec("INSERT INTO wallet_entries(id,customer_id,delta_irt,kind,order_id,actor,balance_after) VALUES('legacy-shaped',1,-10,'order_payment','new-token','customer',490)");assert.equal(c.prepare("SELECT payment_token FROM wallet_entries WHERE id='legacy-shaped'").get()!.payment_token,'new-token');c.exec(`INSERT INTO orders(id,customer_id,state,selections,amount,idempotency_key,verified_by) VALUES('new-order',1,'approved','{"wallet":{"credit_irt":10}}',0,'new-token','wallet')`);assert.equal(c.prepare("SELECT order_id FROM wallet_entries WHERE id='legacy-shaped'").get()!.order_id,'new-order');assert.throws(()=>c.exec(`INSERT INTO orders(id,customer_id,state,selections,amount,idempotency_key,verified_by) VALUES('substitution',2,'approved','{"wallet":{"credit_irt":10}}',0,'different-token','wallet')`));assert.deepEqual(c.prepare('PRAGMA foreign_key_check').all(),[]);}finally{c.close();}});

test('ambiguous historical payment tokens stop migration transaction without altering financial records',()=>{const c=baseline();try{c.exec("INSERT INTO wallet_entries(id,customer_id,delta_irt,kind,order_id,actor,balance_after) VALUES('ambiguous',1,-100,'order_payment','historical-token','customer',400)");const seeded=snapshot(c);c.exec('BEGIN');assert.throws(()=>c.exec(sql),/UNIQUE/);c.exec('ROLLBACK');assert.deepEqual(snapshot(c),seeded);assert.deepEqual(c.prepare('PRAGMA foreign_key_check').all(),[]);}finally{c.close();}});
