import {test,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import type {DatabaseSync} from 'node:sqlite';
import {freshDb,makeD1Shim,ADMIN,USER,messageUpdateAs,makeFetchStub} from './helpers.ts';
import {payOrderWithWallet,refundOrderWalletPayment,recoverUnlinkedWalletPayments} from '../src/db/wallet.ts';
import {insertOrderWithEvent} from '../src/db/orders.ts';
import {claimUpdate,UpdateClaimUnavailable} from '../src/db/dedupe.ts';
import {handleWebhook} from '../src/routes/webhook.ts';
import {newOrderId} from '../src/lib/security.ts';
import {TelegramApi} from '../src/telegram/api.ts';
import {deliverMigrationNotices} from '../src/handlers/serviceMigration.ts';
import {createAnnouncement,startAnnouncement,runAnnouncementChunk,sweepStuckDeliveries,announcementAggregate,ANNOUNCE_LEASE_MS} from '../src/db/announcements.ts';
import {runAnnouncementSweep,runAnnouncementPass} from '../src/handlers/announcements.ts';
import type {Env,TelegramApiLike,UpdateContext} from '../src/types.ts';
let raw:DatabaseSync,db:D1Database,env:Env,originalFetch:typeof fetch;
beforeEach(()=>{raw=freshDb();db=makeD1Shim(raw) as unknown as D1Database;env={DB:db,TELEGRAM_BOT_TOKEN:'SYNTHETIC-RELIABILITY',TELEGRAM_WEBHOOK_SECRET:'SYNTHETIC-WEBHOOK',ADMIN_CHAT_ID:String(ADMIN.id)};
 raw.prepare('INSERT INTO customers(id,telegram_user_id,balance_irt) VALUES(1,?,500),(2,?,500)').run(String(USER.id),String(ADMIN.id));originalFetch=fetch;});
afterEach(()=>{globalThis.fetch=originalFetch;raw.close();});
const wallet=(orderId:string,customerId=1,amountIrt=100)=>payOrderWithWallet(db,{customerId,amountIrt,orderId,actor:'test'});
const balance=()=>raw.prepare('SELECT balance_irt v FROM customers WHERE id=1').get()!.v;
function synchronizeBalanceReads(){const base=db;let n=0,release!:()=>void;const barrier=new Promise<void>(r=>release=r);
 db={...base,prepare(sql:string){const s=base.prepare(sql);if(sql==='SELECT balance_irt FROM customers WHERE id = ?1'){const f=s.first.bind(s);s.first=(async()=>{const value=await f();if(++n<=2){if(n===2)release();await barrier;}return value;}) as typeof s.first;}return s;}} as D1Database;env.DB=db;}
test('different orders with synchronized pre-reads debit exactly two SQL-ledger claims',async()=>{synchronizeBalanceReads();const out=await Promise.all([wallet('different-A'),wallet('different-B')]);assert.ok(out.every(r=>r.ok));assert.equal(balance(),300);assert.equal(raw.prepare("SELECT count(*) n,SUM(delta_irt) delta FROM wallet_entries WHERE kind='order_payment'").get()!.n,2);assert.equal(raw.prepare('SELECT SUM(delta_irt) d FROM wallet_entries').get()!.d,-200);});
test('same-order simultaneous retries charge once and converge on one claim',async()=>{synchronizeBalanceReads();const out=await Promise.all([wallet('same'),wallet('same')]);assert.ok(out.every(r=>r.ok));assert.equal(balance(),400);assert.equal(raw.prepare('SELECT COUNT(*) n FROM wallet_entries').get()!.n,1);});
test('different orders compete for insufficient funds without negative balance or phantom ledger',async()=>{raw.prepare('UPDATE customers SET balance_irt=150 WHERE id=1').run();synchronizeBalanceReads();const out=await Promise.all([wallet('one'),wallet('two')]);assert.equal(out.filter(r=>r.ok).length,1);assert.equal(balance(),50);assert.equal(raw.prepare('SELECT count(*) n FROM wallet_entries').get()!.n,1);});
test('failure after ledger claim rolls back ledger and debit in actual SQLite transaction',async()=>{raw.exec("CREATE TRIGGER synthetic_fail BEFORE UPDATE OF balance_irt ON customers BEGIN SELECT RAISE(ABORT,'synthetic'); END;");assert.equal((await wallet('rollback')).ok,false);assert.equal(balance(),500);assert.equal(raw.prepare('SELECT count(*) n FROM wallet_entries').get()!.n,0);});
test('uncertain batch response reconciles committed ledger and never repeats debit',async()=>{const base=db;db={...base,async batch(stmts){await base.batch(stmts);throw Error('synthetic lost response');}} as D1Database;assert.equal((await wallet('unknown')).ok,true);db=base;assert.equal((await wallet('unknown')).ok,true);assert.equal(balance(),400);});
test('stable draft payment token survives atomic order-link and replay cannot recharge',async()=>{const token=newOrderId(),id=newOrderId();await wallet(token);await insertOrderWithEvent(db,{id,customerId:1,amount:0,currency:'IRT',idempotencyKey:token,selections:JSON.stringify({wallet:{credit_irt:100,mode:'full'}}),initialState:'approved',verifiedBy:'wallet'});assert.equal(raw.prepare('SELECT order_id FROM wallet_entries WHERE payment_token=?').get(token)!.order_id,id);assert.equal((await wallet(token)).ok,true);assert.equal(balance(),400);assert.equal(raw.prepare('SELECT count(*) n FROM order_events WHERE order_id=?').get(id)!.n,1);});
test('customer or amount substitution cannot adopt another wallet claim',async()=>{await wallet('owned');assert.equal((await wallet('owned',2)).ok,false);assert.equal((await wallet('owned',1,50)).ok,false);assert.equal(balance(),400);});
test('funded approved order cannot be inserted without matching unrefunded wallet claim',async()=>{await assert.rejects(()=>insertOrderWithEvent(db,{id:newOrderId(),customerId:1,amount:0,currency:'IRT',idempotencyKey:newOrderId(),selections:'{"wallet":{"credit_irt":100}}',initialState:'approved',verifiedBy:'wallet'}));assert.equal(raw.prepare('SELECT COUNT(*) n FROM orders').get()!.n,0);assert.equal(balance(),500);});
test('refund is atomic and cannot be reapplied after a different later payment lowers balance',async()=>{await wallet('refund');assert.equal(await refundOrderWalletPayment(db,{customerId:1,orderId:'refund',actor:'test'}),true);await wallet('later');await refundOrderWalletPayment(db,{customerId:1,orderId:'refund',actor:'test'});assert.equal(balance(),400);assert.equal(raw.prepare("SELECT count(*) n FROM wallet_entries WHERE kind='order_refund'").get()!.n,1);assert.equal((await wallet('refund')).ok,false);});
test('orphan pre-order payment recovers after cutoff once, and late funded insertion is rejected',async()=>{const token=newOrderId();await wallet(token);raw.prepare("UPDATE wallet_entries SET created_at='2020-01-01T00:00:00Z'").run();await recoverUnlinkedWalletPayments(db);await recoverUnlinkedWalletPayments(db);assert.equal(balance(),500);await assert.rejects(()=>insertOrderWithEvent(db,{id:newOrderId(),customerId:1,amount:0,currency:'IRT',idempotencyKey:token,selections:'{"wallet":{"credit_irt":100}}',initialState:'approved'}));assert.equal(raw.prepare("SELECT count(*) n FROM wallet_entries WHERE kind='order_refund'").get()!.n,1);});
test('linked approved order and fresh reservation are not refunded by orphan recovery',async()=>{const token=newOrderId();await wallet(token);await insertOrderWithEvent(db,{id:newOrderId(),customerId:1,amount:0,currency:'IRT',idempotencyKey:token,selections:'{"wallet":{"credit_irt":100}}',initialState:'approved'});raw.prepare("UPDATE wallet_entries SET created_at='2020-01-01T00:00:00Z'").run();await wallet('fresh');await recoverUnlinkedWalletPayments(db);assert.equal(balance(),300);assert.equal(raw.prepare("SELECT count(*) n FROM wallet_entries WHERE kind='order_refund'").get()!.n,0);});
test('real duplicate dedupe is a confirmed no-op, not a caught operational exception',async()=>{assert.equal(await claimUpdate(db,101),'fresh');assert.equal(await claimUpdate(db,101),'replay');});
test('dedupe INSERT, cleanup and unverifiable-result failures propagate typed retryable errors',async()=>{for(const mode of ['insert','cleanup','meta']){const base=db;const broken={...base,prepare(sql:string){if((mode==='insert'&&sql.startsWith('INSERT'))||(mode==='cleanup'&&sql.startsWith('DELETE')))throw Error('synthetic secret upstream');const s=base.prepare(sql);if(mode==='meta')s.run=(async()=>({success:true})) as typeof s.run;return s;}} as D1Database;await assert.rejects(()=>claimUpdate(broken,111),UpdateClaimUnavailable);}});
test('webhook returns503 on unavailable dedupe and redelivery succeeds exactly once after recovery',async()=>{const base=db;env.DB={...base,prepare(sql:string){if(sql.startsWith('INSERT INTO update_dedupe'))throw Error('synthetic D1 outage');return base.prepare(sql);}} as D1Database;const update=messageUpdateAs(USER,'/myid',909);
 const request=()=>new Request('https://synthetic.example.com/telegram/webhook',{method:'POST',headers:{'x-telegram-bot-api-secret-token':env.TELEGRAM_WEBHOOK_SECRET},body:JSON.stringify(update)});
 const failed=await handleWebhook(request(),env);assert.equal(failed.status,503);assert.equal(failed.headers.get('retry-after'),'5');assert.ok(!(await failed.text()).includes('synthetic D1'));env.DB=base;const stub=makeFetchStub();try{assert.equal((await handleWebhook(request(),env)).status,200);const count=stub.sent.length;assert.equal((await handleWebhook(request(),env)).status,200);assert.equal(stub.sent.length,count);}finally{stub.restore();}});
async function noticeFixture(){const service=newOrderId(),m=newOrderId();raw.prepare("INSERT INTO panels(id,name,origin,auth_type,group_ids) VALUES('dest','dest','https://synthetic.example.com','api_key','[1]')").run();raw.prepare("INSERT INTO orders(id,customer_id,state,selections,amount,panel_id,pasarguard_user_id,pasarguard_username) VALUES(?,1,'completed','{}',0,'legacy','1','originalname')").run(service);
 raw.prepare(`INSERT INTO service_migrations(id,service_id,customer_id,operator,source_panel_id,source_origin,source_user_id,source_username,destination_panel_id,destination_origin,destination_revision,destination_username,destination_user_id,destination_url,destination_config,state,entitlement,confirmed_by,confirmation_token,review_expires_at)
 VALUES(?,?,1,?,'legacy','https://source.example.com','1','originalname','dest','https://synthetic.example.com',1,?,'2','https://synthetic.example.com/sub/new','{"groupIds":[1]}','activating','{}',?,'synthetic-token',9999999999999)`)
 .run(m,service,String(ADMIN.id),'mg'+m.toLowerCase(),String(ADMIN.id));raw.prepare("INSERT INTO active_service_resources(service_id,migration_id,panel_id,user_id,username,subscription_url,expires_at,provision_config) VALUES(?,?,'dest','2',?,'https://synthetic.example.com/sub/new','2030-01-01','{}')").run(service,m,'mg'+m.toLowerCase());raw.prepare("UPDATE service_migrations SET state='cleanup_pending' WHERE id=?").run(m);return m;}
for(const mode of ['api_error','network_timeout','invalid_response','rate_limit'])test(`migration notice ${mode} stays recoverable; confirmed retry stamps once`,async()=>{const m=await noticeFixture();let sends=0;globalThis.fetch=async()=>{sends++;if(mode==='network_timeout')throw new DOMException('synthetic','TimeoutError');return mode==='invalid_response'?Response.json({ok:true,result:{}}):Response.json({ok:false,error_code:mode==='rate_limit'?429:503,parameters:{retry_after:1}},{status:mode==='rate_limit'?429:503});};await deliverMigrationNotices(env);assert.equal(raw.prepare('SELECT customer_notified_at FROM service_migrations WHERE id=?').get(m)!.customer_notified_at,null);globalThis.fetch=async()=>{sends++;return Response.json({ok:true,result:{message_id:99}})};await deliverMigrationNotices(env);assert.ok(raw.prepare('SELECT customer_notified_at FROM service_migrations WHERE id=?').get(m)!.customer_notified_at);const before=sends;await deliverMigrationNotices(env);assert.equal(sends,before);});
async function announcement(total=2){for(let n=3;n<=total;n++)raw.prepare('INSERT INTO customers(id,telegram_user_id) VALUES(?,?)').run(n,String(100000+n));const j=(await createAnnouncement(db,{body:'SYNTHETIC-BROADCAST',createdBy:`admin:${ADMIN.id}`,totalEstimate:total}))!;await startAnnouncement(db,j.id);return j;}
function harness(){let time=Date.now();const recipients:number[]=[];const api={sendMessage:async()=>({message_id:1}),sendMessageDelivery:async(chat:number)=>{recipients.push(chat);return {kind:'sent',messageId:chat};}} as TelegramApiLike;
 return {api,recipients,runtime:{now:()=>time,sleep:async(ms:number)=>{time+=ms}},advance:(ms:number)=>{time+=ms}};}
test('more than20 recipients continue automatically with no repeated administrator callback',async()=>{const j=await announcement(75),h=harness();assert.equal(await runAnnouncementChunk(db,h.api,j.body,j.id,20,h.runtime),20);assert.equal(raw.prepare('SELECT state FROM announcements WHERE id=?').get(j.id)!.state,'sending');for(let i=0;i<10;i++){h.advance(300000);await runAnnouncementSweep(env,h.api,h.runtime);if(raw.prepare('SELECT state FROM announcements WHERE id=?').get(j.id)!.state==='done')break;}const a=await announcementAggregate(db,j.id);assert.equal(a.total,75);assert.equal(a.sent,75);assert.equal(a.failed,0);assert.equal(a.pending,0);assert.equal(h.recipients.length,75);assert.equal(new Set(h.recipients).size,75);});
test('2000-person audience across bounded seeding and delivery chunks eventually terminates automatically',async()=>{const j=await announcement(2000),h=harness();for(let i=0;i<70;i++){await runAnnouncementSweep(env,h.api,h.runtime);h.advance(300000);if(raw.prepare('SELECT state FROM announcements WHERE id=?').get(j.id)!.state==='done')break;}assert.equal(raw.prepare('SELECT state FROM announcements WHERE id=?').get(j.id)!.state,'done');const a=await announcementAggregate(db,j.id);assert.equal(a.sent,2000);assert.equal(a.total,2000);assert.equal(h.recipients.length,2000);assert.equal(new Set(h.recipients).size,2000);});
test('drafts are never auto-started and ordinary users cannot confirm them',async()=>{const j=(await createAnnouncement(db,{body:'DRAFT',createdBy:`admin:${ADMIN.id}`,totalEstimate:2}))!,h=harness();await runAnnouncementSweep(env,h.api,h.runtime);assert.equal(h.recipients.length,0);const ctx={env,db,api:{...h.api,answerCallbackQuery:async()=>{}},actor:USER,customerId:1,chatId:USER.id,isAdmin:false} as UpdateContext;await runAnnouncementPass(ctx,j.id,'synthetic',null,null);assert.equal(raw.prepare('SELECT started_at FROM announcements WHERE id=?').get(j.id)!.started_at,null);assert.equal(raw.prepare('SELECT count(*) n FROM announcement_deliveries').get()!.n,0);});
test('live recipient leases are not reclaimed and overlapping workers send only their own claims',async()=>{const j=await announcement(6),h=harness();let release!:()=>void,started!:()=>void;const holding=new Promise<void>(r=>release=r),entered=new Promise<void>(r=>started=r);let first=true;const base=h.api.sendMessageDelivery!;h.api.sendMessageDelivery=async(...args)=>{if(first){first=false;started();await holding;}return base(...args)};
 const a=runAnnouncementChunk(db,h.api,j.body,j.id,20,h.runtime);await entered;assert.equal(await sweepStuckDeliveries(db,j.id,h.runtime.now()),0);assert.equal(await runAnnouncementChunk(db,h.api,j.body,j.id,20,h.runtime),0);release();await a;assert.equal(h.recipients.length,6);assert.equal(new Set(h.recipients).size,6);});
test('worker restart reclaims expired claims but never classifies unknown acceptance as success',async()=>{const j=await announcement(2),h=harness();await import('../src/db/announcements.ts').then(m=>m.seedAnnouncementDeliveries(db,j.id));raw.prepare("UPDATE announcement_deliveries SET status='sending',claim_owner='old-worker',lease_until=?,attempt_started_at=?,attempts=1 WHERE announcement_id=? AND customer_id=1").run(h.runtime.now()-1,h.runtime.now()-200000,j.id);
 assert.equal((await announcementAggregate(db,j.id)).sent,0);await runAnnouncementSweep(env,h.api,h.runtime);assert.equal((await announcementAggregate(db,j.id)).sent,2);assert.equal(raw.prepare('SELECT failure_attempts FROM announcement_deliveries WHERE announcement_id=? AND customer_id=1').get(j.id)!.failure_attempts,1);});
test('429 pauses global broadcast dispatch without burning recipient failure budget; resumes after retry_after',async()=>{const j=await announcement(3),h=harness();let calls=0;h.api.sendMessageDelivery=async(chat)=>{calls++;if(calls===1)return {kind:'rate_limited',retryAfter:120};h.recipients.push(chat);return {kind:'sent',messageId:chat}};assert.equal(await runAnnouncementChunk(db,h.api,j.body,j.id,20,h.runtime),1);await runAnnouncementSweep(env,h.api,h.runtime);assert.equal(calls,1);h.advance(121000);await runAnnouncementSweep(env,h.api,h.runtime);assert.equal((await announcementAggregate(db,j.id)).sent,3);assert.equal(raw.prepare('SELECT SUM(failure_attempts) n FROM announcement_deliveries').get()!.n,0);});
test('blocked/invalid recipients are terminal failures; successful and retryable recipients stay accurately classified',async()=>{const j=await announcement(4),h=harness();let tries=0;h.api.sendMessageDelivery=async(chat)=>{if(chat===USER.id)return {kind:'permanent',code:'telegram_recipient_rejected'};if(chat===ADMIN.id&&tries++===0)return {kind:'retryable',code:'telegram_unavailable'};return {kind:'sent',messageId:chat}};raw.prepare("UPDATE customers SET telegram_user_id='invalid-synthetic' WHERE id=4").run();await runAnnouncementSweep(env,h.api,h.runtime);let a=await announcementAggregate(db,j.id);assert.equal(a.sent,1);assert.equal(a.failed,2);assert.equal(a.pending,1);assert.equal(a.retryable,1);assert.equal(a.delayed,1);h.advance(61000);await runAnnouncementSweep(env,h.api,h.runtime);a=await announcementAggregate(db,j.id);assert.equal(a.sent,2);assert.equal(a.failed,2);assert.equal(a.pending,0);assert.equal(raw.prepare('SELECT state FROM announcements WHERE id=?').get(j.id)!.state,'done');});
for(const kind of ['retryable','unknown'] as const)test(`repeated ${kind} responses exhaust bounded retries without recording success`,async()=>{const j=await announcement(),h=harness();h.api.sendMessageDelivery=async()=>({kind,code:'synthetic-unconfirmed'});for(let i=0;i<4;i++){await runAnnouncementSweep(env,h.api,h.runtime);h.advance(61000);}const a=await announcementAggregate(db,j.id);assert.equal(a.sent,0);assert.equal(a.failed,2);assert.equal(a.pending,0);assert.equal(raw.prepare('SELECT MAX(attempts) n FROM announcement_deliveries WHERE announcement_id=?').get(j.id)!.n,3);});
test('bot authentication errors pause recoverably rather than marking the whole audience blocked',async()=>{const j=await announcement(),h=harness();h.api.sendMessageDelivery=async()=>({kind:'configuration',code:'telegram_auth_unavailable'});await runAnnouncementSweep(env,h.api,h.runtime);const a=await announcementAggregate(db,j.id);assert.equal(a.sent,0);assert.equal(a.failed,0);assert.equal(a.pending,2);assert.ok(Number(raw.prepare('SELECT pause_until FROM announcement_dispatch').get()!.pause_until)>h.runtime.now());});
test('deadline releases only unattempted claims; subsequent automatic execution finishes them',async()=>{const j=await announcement(),h=harness();let first=true;const base=h.api.sendMessageDelivery!;h.api.sendMessageDelivery=async(...args)=>{const out=await base(...args);if(first){first=false;h.advance(20000);}return out};await runAnnouncementChunk(db,h.api,j.body,j.id,20,h.runtime);let a=await announcementAggregate(db,j.id);assert.equal(a.sent,1);assert.equal(a.pending,1);assert.equal(a.stuck,0);h.advance(300000);await runAnnouncementSweep(env,h.api,h.runtime);assert.equal((await announcementAggregate(db,j.id)).sent,2);assert.equal(h.recipients.length,2);});
test('booking failure after acceptance leaves attempted claim leased until safe expiry, not immediately retryable',async()=>{const j=await announcement(),h=harness(),base=db;let thrown=false;const failing={...base,prepare(sql:string){if(sql.includes('failure_attempts=failure_attempts+?6')&&!thrown){thrown=true;throw Error('synthetic booking unavailable')}return base.prepare(sql)}} as D1Database;
 await assert.rejects(()=>runAnnouncementChunk(failing,h.api,j.body,j.id,20,h.runtime));assert.equal(h.recipients.length,1);const r=raw.prepare('SELECT status,lease_until FROM announcement_deliveries WHERE announcement_id=? AND customer_id=1').get(j.id)!;assert.equal(r.status,'sending');assert.ok(Number(r.lease_until)>h.runtime.now());await runAnnouncementSweep(env,h.api,h.runtime);assert.equal(h.recipients.filter(n=>n===USER.id).length,1);h.advance(ANNOUNCE_LEASE_MS+1);await runAnnouncementSweep(env,h.api,h.runtime);assert.equal((await announcementAggregate(db,j.id)).sent,2);assert.equal(h.recipients.filter(n=>n===USER.id).length,2,'documented at-least-once unknown outcome, not simultaneous ownership');});
test('one blocked job does not starve another ready announcement',async()=>{const a=await announcement(),b=await announcement(),h=harness();await import('../src/db/announcements.ts').then(async m=>{await m.seedAnnouncementDeliveries(db,a.id);await m.seedAnnouncementDeliveries(db,b.id)});raw.prepare('UPDATE announcement_deliveries SET next_attempt_at=? WHERE announcement_id=?').run(h.runtime.now()+600000,a.id);await runAnnouncementSweep(env,h.api,h.runtime);assert.equal((await announcementAggregate(db,b.id)).sent,2);assert.equal((await announcementAggregate(db,a.id)).sent,0);});
test('audience boundary is durable and no repeated seed scans include post-confirmation joiners',async()=>{const j=await announcement(205),h=harness();raw.prepare("INSERT INTO customers(id,telegram_user_id) VALUES(206,'200206')").run();for(let i=0;i<10;i++){await runAnnouncementSweep(env,h.api,h.runtime);h.advance(300000);}assert.equal((await announcementAggregate(db,j.id)).sent,205);assert.equal(raw.prepare('SELECT COUNT(*) n FROM announcement_deliveries WHERE customer_id=206').get()!.n,0);assert.equal(raw.prepare('SELECT audience_highwater FROM announcements WHERE id=?').get(j.id)!.audience_highwater,205);});
for(const scenario of ['success','blocked','rate_limit','server_failure','timeout','malformed'])test(`structured Telegram transport classifies ${scenario} without leaking data`,async()=>{const api=new TelegramApi('SYNTHETIC-NOT-A-SECRET');globalThis.fetch=async(_input,init)=>{assert.equal(init?.redirect,'error');assert.ok(init?.signal);if(scenario==='timeout')throw new DOMException('synthetic secret','TimeoutError');if(scenario==='success')return Response.json({ok:true,result:{message_id:77}});if(scenario==='malformed')return Response.json({ok:true,result:{}});const code=scenario==='blocked'?403:scenario==='rate_limit'?429:503;return Response.json({ok:false,error_code:code,description:'synthetic secret material',parameters:{retry_after:123}},{status:code})};const out=await api.sendMessageDelivery(USER.id,'synthetic');assert.equal(out.kind,{success:'sent',blocked:'permanent',rate_limit:'rate_limited',server_failure:'retryable',timeout:'unknown',malformed:'unknown'}[scenario]);assert.ok(!JSON.stringify(out).includes('secret'));if(out.kind==='rate_limited')assert.equal(out.retryAfter,123);});

test('legacy historical order without idempotency key cannot be refunded as an orphan',async()=>{const id=newOrderId();await wallet(id);raw.prepare("INSERT INTO orders(id,customer_id,state,selections,amount,panel_id) VALUES(?,1,'completed','{}',100,'legacy')").run(id);raw.prepare("UPDATE wallet_entries SET created_at='2020-01-01T00:00:00Z'").run();await recoverUnlinkedWalletPayments(db);assert.equal(await refundOrderWalletPayment(db,{customerId:1,orderId:id,actor:'system:wallet-checkout-recovery',onlyIfUnlinkedBefore:new Date().toISOString()}),false);assert.equal(balance(),400);assert.equal(raw.prepare("SELECT COUNT(*) n FROM wallet_entries WHERE kind='order_refund'").get()!.n,0);});

test('expired or substituted announcement owner cannot stamp a delivery as sent',async()=>{const j=await announcement(),h=harness();const module=await import('../src/db/announcements.ts');await module.seedAnnouncementDeliveries(db,j.id);raw.prepare("UPDATE announcement_deliveries SET status='sending',claim_owner='current',lease_until=? WHERE announcement_id=? AND customer_id=1").run(h.runtime.now()+1000,j.id);await module.bookAnnouncementDelivery(db,{announcementId:j.id,customerId:1,owner:'obsolete',delivery:{kind:'sent',messageId:5},now:h.runtime.now()});assert.equal((await announcementAggregate(db,j.id)).sent,0);await module.bookAnnouncementDelivery(db,{announcementId:j.id,customerId:1,owner:'current',delivery:{kind:'sent',messageId:5},now:h.runtime.now()+1001});assert.equal((await announcementAggregate(db,j.id)).sent,0);assert.equal(raw.prepare('SELECT status FROM announcement_deliveries WHERE announcement_id=? AND customer_id=1').get(j.id)!.status,'sending');});
