/** Static localized shell; no panel metadata or stored credential in HTML. */
import {uiFor,type Locale} from '../telegram/i18n.ts';
export function renderPanelForm(token:string,scriptNonce:string,locale:Locale):string{
 const {t}=uiFor(locale);
 const strings=Object.fromEntries(Object.entries(t).filter(([k,v])=>k.startsWith('panelForm')||k.startsWith('panelGroups')||k==='panelTestGroupsMissing'));
 const serialized=JSON.stringify(strings).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="${locale}" dir="${locale==='fa'?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="errf-group-status-version" content="status-evidence-v1"><meta name="errf-panel-form-version" content="cloudflare-bindings-v1"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t.panelFormTitle}</title>
<style nonce="${scriptNonce}">
:root{color-scheme:light dark;--canvas:#f6f7f9;--surface:#fff;--text:#17212b;--muted:#526271;--border:#d8dfe7;--accent:#1767ba;--soft:#edf4fc;--error:#a52c29}
*{box-sizing:border-box}body{font:16px/1.5 system-ui,-apple-system,sans-serif;max-width:552px;margin:24px auto;padding:16px;background:var(--canvas);color:var(--text)}h1{font-size:26px;margin:0 0 8px}p{margin:8px 0 20px;color:var(--muted)}label{display:block}input:not([type=checkbox]),button{font:inherit;width:100%;padding:12px;margin:8px 0;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:var(--text)}input[type=checkbox]{width:20px;height:20px;margin:0;accent-color:var(--accent);flex:0 0 20px}input[type=url],input[type=password]{direction:ltr;text-align:left}input:focus-visible,button:focus-visible{outline:3px solid var(--accent);outline-offset:3px}button{min-height:48px;cursor:pointer}button:disabled{opacity:.55;cursor:default}#save{color:#fff;background:var(--accent);border-color:var(--accent);margin-top:20px}fieldset{border:0;padding:0;margin:0}.selector{background:var(--surface);border:1px solid var(--border);border-radius:12px;margin-top:20px;padding:16px}.selector h2{font-size:18px;margin:0 0 4px}.hint{font-size:14px;margin-bottom:12px}.check-row{display:flex;gap:12px;align-items:center;min-height:48px;padding:12px;cursor:pointer;border:1px solid var(--border);border-radius:8px;margin-top:8px}.check-row:has(input:checked){background:var(--soft);border-color:var(--accent)}.check-row span{overflow-wrap:anywhere;min-width:0}.select-all{font-weight:600;margin-top:0}#group-list{max-height:280px;overflow-y:auto;padding:0 2px 2px}#group-count{font-size:14px;margin-top:12px}#group-state,#group-warning,#status{overflow-wrap:anywhere}#group-state[data-error=true],#group-warning{color:var(--error)}#group-state{margin:12px 0 0}#group-warning{font-size:14px;margin:8px 0 0}[hidden]{display:none!important}
@media(max-width:420px){body{margin:8px auto;padding:16px}.selector{padding:12px}}
@media(prefers-color-scheme:dark){:root{--canvas:#191919;--surface:#202020;--text:#f5f5f5;--muted:#bdc6d0;--border:#59616b;--accent:#64a9ee;--soft:#253447;--error:#ffaaa5}#save{color:#142536}}
</style></head><body><h1 id="title">${t.panelFormTitle}</h1><p id="intro">${t.panelFormIntro}</p>
<form id="f"><fieldset id="fields" disabled hidden>
<label>${t.panelFormName}<input id="name" maxlength="64" required></label>
<label id="url-row">${t.panelFormOrigin}<input id="url" type="url" required placeholder="https://panel.example.com" autocomplete="off"></label>
<label id="key-row"><span id="key-label">${t.panelFormKey}</span><input id="key" type="password" autocomplete="off" maxlength="4096" required></label>
<section id="groups-row" class="selector" aria-labelledby="group-title"><h2 id="group-title">${t.panelGroupsTitle}</h2><p class="hint">${t.panelGroupsHint}</p>
<button id="load-groups" type="button">${t.panelGroupsLoad}</button><div id="group-controls" hidden><label class="check-row select-all"><input type="checkbox" id="select-all"><span>${t.panelGroupsSelectAll}</span></label><div id="group-list"></div><div id="group-count" role="status" aria-live="polite"></div></div>
<button id="verify-groups" type="button" hidden>${t.panelGroupsVerifyStatus}</button><p id="group-state" role="status" aria-live="polite">${t.panelGroupsPrompt}</p><p id="group-diagnostic" dir="ltr" hidden></p><p id="group-warning" hidden></p><button id="group-retry" type="button" hidden>${t.panelGroupsRetry}</button></section>
<button id="save" type="submit" disabled>${t.panelFormSave}</button></fieldset></form><p id="status" role="status" aria-live="polite">${t.panelFormAuthenticating}</p>
<script src="https://telegram.org/js/telegram-web-app.js"></script><script nonce="${scriptNonce}">
const t=${serialized},token='${token}';
const $=id=>document.getElementById(id),f=$('f'),fields=$('fields'),out=$('status'),key=$('key'),button=$('save'),all=$('select-all'),list=$('group-list'),state=$('group-state'),retry=$('group-retry'),loadButton=$('load-groups'),verifyButton=$('verify-groups'),diagnostic=$('group-diagnostic');
let ready=false,legacy=false,managed=false,hasKey=false,available=[],selected=new Set(),desired=[],groupsReady=false,epoch=0,timer=null,lastOrigin='',rows=[],verifying=false;
const initData=()=>window.Telegram?.WebApp?.initData;
const errors={permission_denied:t.panelGroupsPermission,key_rejected:t.panelGroupsKeyRejected,origin_locked:t.panelGroupsOriginLocked,invalid_origin:t.panelGroupsInvalidOrigin,key_required:t.panelGroupsKeyRequired,unsupported_api:t.panelGroupsUnsupported,session_changed:t.panelGroupsSessionChanged,destination_check_failed:t.panelGroupsDestinationFailed,managed_configuration_locked:t.panelFormManagedLocked,managed_configuration_unavailable:t.panelFormManagedUnavailable,groups_missing:t.panelTestGroupsMissing,groups_none_available:t.panelGroupsEmpty,groups_none_enabled:t.panelGroupsNoneEnabled,groups_invalid_configuration:t.panelGroupsConfigInvalid,group_disabled:t.panelGroupsDisabledError,group_not_found:t.panelGroupsNotFound,group_response_unexpected:t.panelGroupsUnexpected,groups_status_unverified:t.panelGroupsStatusUnverified,group_details_permission_denied:t.panelGroupsDetailsPermission,account_permission_denied:t.panelGroupsAccountPermission,status_verification_failed:t.panelGroupsVerificationFailed,status_api_unavailable:t.panelGroupsStatusApiUnavailable};
const endpoints={metadata:'/admin/panels/metadata',groups:'/admin/panels/groups',configure:'/admin/panels/configure'};
async function post(path,extra={}){if(!initData())throw Error();return fetch(endpoints[path],{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({nonce:token,initData:initData(),...extra})});}
function summary(){const count=selected.size;all.checked=available.length>0&&count===available.length;all.indeterminate=count>0&&count<available.length;$('group-count').textContent=count===1?t.panelGroupsCountOne:t.panelGroupsCountMany.replace('{count}',String(count));const over=count>50;$('group-warning').hidden=!over&&$('group-warning').textContent==='';if(over){$('group-warning').textContent=t.panelGroupsLimit;$('group-warning').hidden=false;}else if($('group-warning').textContent===t.panelGroupsLimit){$('group-warning').textContent='';$('group-warning').hidden=true;}verifyButton.disabled=!ready||verifying||count===0||over;button.disabled=!ready||verifying||(!legacy&&(!groupsReady||count===0||over||[...selected].some(id=>available.find(g=>g.id===id)?.statusVerified===false)));}
function status(message,error=false){state.textContent=message;state.setAttribute('data-error',String(error));}
function invalidate(){diagnostic.hidden=true;diagnostic.textContent='';epoch++;verifying=false;verifyButton.hidden=true;rows=[];groupsReady=false;available=[];selected.clear();list.replaceChildren();$('group-controls').hidden=true;retry.hidden=true;status(t.panelGroupsPrompt);summary();}
function origin(){try{const raw=$('url').value;if(/[\\x00-\\x1f\\x7f]/.test(raw))return '';const u=new URL(raw.trim());if(u.protocol!=='https:'||u.username||u.password||u.search||(u.port&&u.port!=='443'&&u.port!=='8000'))return '';return u.origin;}catch{return '';}}
function render(groups){diagnostic.hidden=true;diagnostic.textContent='';rows=groups;list.replaceChildren();available=groups.filter(g=>g.disabled!==true);selected=new Set(desired.filter(id=>available.some(g=>g.id===id)));const missing=desired.some(id=>!selected.has(id));$('group-warning').textContent=missing?t.panelGroupsMissing:'';$('group-warning').hidden=!missing;
 for(const group of groups){const row=document.createElement('label'),input=document.createElement('input'),name=document.createElement('span');row.className='check-row';input.type='checkbox';input.value=String(group.id);input.checked=selected.has(group.id);input.disabled=group.disabled===true;name.textContent=group.name+(group.disabled===true?' — '+t.panelGroupsDisabledLabel:'');name.dir='auto';input.onchange=()=>{if(input.disabled)return;if(input.checked)selected.add(group.id);else selected.delete(group.id);desired=[...selected];summary();};row.append(input,name);list.append(row);}
 $('group-controls').hidden=available.length===0;const unverified=groups.some(g=>g.statusVerified===false);groupsReady=available.length>0;verifyButton.hidden=!unverified;status(unverified?t.panelGroupsStatusUnverified:available.length?'':groups.length?t.panelGroupsNoneEnabled:t.panelGroupsEmpty,unverified);retry.hidden=available.length>0;summary();}
async function discover(){if(!ready||legacy)return;const attempt=++epoch,destination=origin();verifying=false;verifyButton.disabled=true;if(!destination){groupsReady=false;status(t.panelGroupsInvalidOrigin,true);retry.hidden=false;summary();return;}groupsReady=false;button.disabled=true;loadButton.disabled=true;retry.hidden=true;$('group-controls').hidden=true;status(t.panelGroupsLoading);try{const r=await post('groups',{url:$('url').value,apiKey:key.value});const data=await r.json();if(attempt!==epoch)return;if(!r.ok){status(errors[data.code]||(r.status===403?t.panelFormAuthError:t.panelGroupsError),true);retry.hidden=false;return;}if(!Array.isArray(data.groups)||data.groups.some(g=>!Number.isSafeInteger(g.id)||g.id<1||typeof g.name!=='string'||(g.disabled!==undefined&&typeof g.disabled!=='boolean')||(g.statusVerified!==undefined&&g.statusVerified!==false)))throw Error();$('url').value=destination;lastOrigin=destination;render(data.groups);}catch{if(attempt===epoch){status(t.panelGroupsError,true);retry.hidden=false;}}finally{if(attempt===epoch){loadButton.disabled=false;summary();}}}
async function verifySelected(){if(!ready||!groupsReady||verifying||!selected.size||selected.size>50)return;const attempt=epoch,ids=[...selected].sort((a,b)=>a-b),signature=JSON.stringify(ids);verifying=true;desired=[...selected];render(rows.map(g=>ids.includes(g.id)?{id:g.id,name:g.name,statusVerified:false}:g));summary();status(t.panelGroupsVerifyingStatus);try{const r=await post('groups',{url:$('url').value,apiKey:key.value,verifyIds:ids,diagnostics:true});const data=await r.json();if(attempt!==epoch||JSON.stringify([...selected].sort((a,b)=>a-b))!==signature)return;if(!r.ok){status(errors[data.code]||(r.status===403?t.panelFormAuthError:t.panelGroupsVerificationFailed),true);const a=data.diagnostic?.attempts;if(Array.isArray(a)&&a.length<=60&&a.every(v=>v.method==='GET'&&typeof v.endpoint==='string'&&/^\\/api\\/(?:group\\/[1-9][0-9]{0,6}|groups\\?offset=[0-9]{1,4}&limit=100)$/.test(v.endpoint)&&(v.httpStatus===null||(Number.isInteger(v.httpStatus)&&v.httpStatus>=100&&v.httpStatus<=599))&&['ok','not_configured','bad_url','network','timeout','auth','permission','identity','not_found','rejected','server','parse'].includes(v.category))){diagnostic.textContent=t.panelGroupsDiagnostic+'\\n'+a.map(v=>'GET '+v.endpoint+' — HTTP '+(v.httpStatus??t.panelGroupsNoResponse)+' — '+v.category).join('\\n');diagnostic.hidden=false;}return;}if(!Array.isArray(data.statuses)||data.statuses.length!==ids.length||new Set(data.statuses.map(g=>g.id)).size!==ids.length||data.statuses.some(g=>!ids.includes(g.id)||typeof g.disabled!=='boolean'))throw Error();const verified=new Map(data.statuses.map(g=>[g.id,g.disabled]));desired=[...selected];render(rows.map(g=>verified.has(g.id)?{id:g.id,name:g.name,disabled:verified.get(g.id)}:g));status(data.statuses.some(g=>g.disabled)?t.panelGroupsDisabledError:t.panelGroupsStatusVerified,data.statuses.some(g=>g.disabled));}catch{if(attempt===epoch)status(t.panelGroupsVerificationFailed,true);}finally{if(attempt===epoch){verifying=false;summary();}}}
verifyButton.onclick=()=>verifySelected();
function changed(){if(groupsReady)desired=[...selected];if(origin()!==lastOrigin)desired=[];invalidate();loadButton.disabled=false;if(timer!==null)clearTimeout(timer);const canLoad=origin().startsWith('https://')&&(key.value!==''||(hasKey&&origin()===lastOrigin));if(canLoad)timer=setTimeout(()=>{timer=null;return discover();},650);}
$('url').oninput=changed;key.oninput=changed;loadButton.onclick=()=>discover();retry.onclick=()=>discover();all.onchange=()=>{selected=new Set(all.checked?available.map(g=>g.id):[]);desired=[...selected];for(const row of list.children)row.children[0].checked=selected.has(Number(row.children[0].value));summary();};
async function load(){try{const r=await post('metadata');if(!r.ok)throw Error();const data=await r.json();$('name').value=data.name;$('url').value=data.url;desired=data.groups;legacy=data.legacy;managed=data.managed===true;hasKey=data.hasApiKey;lastOrigin=origin();key.value='';key.required=!legacy&&!managed&&!hasKey;for(const id of ['url','key']){$(id+'-row').hidden=legacy||(managed&&id==='key');$(id).disabled=legacy||managed;}$('groups-row').hidden=legacy;$('title').textContent=legacy?t.panelFormLegacy:hasKey?t.panelFormEdit:t.panelFormTitle;$('intro').textContent=legacy?t.panelFormLegacyIntro:managed?t.panelFormManagedIntro:t.panelFormIntro;$('key-label').textContent=hasKey?t.panelFormKeepKey:t.panelFormKey;fields.disabled=false;fields.hidden=false;ready=true;out.textContent='';summary();if(!legacy&&hasKey)await discover();}catch{out.textContent=t.panelFormAuthError;}}
f.onsubmit=async e=>{e.preventDefault();if(!ready||button.disabled||(!legacy&&(!groupsReady||selected.size===0||selected.size>50)))return;button.disabled=true;out.textContent=t.panelFormSaving;try{const r=await post('configure',{name:$('name').value,url:$('url').value,apiKey:key.value,groups:legacy?[]:[...selected].sort((a,b)=>a-b)});const data=await r.json();out.textContent=r.ok?(managed?t.panelFormManagedSaved:t.panelFormSaved):(typeof data.code==='string'&&Object.hasOwn(errors,data.code)?errors[data.code]:r.status===403?t.panelFormAuthError:r.status===409?t.panelGroupsSessionChanged:t.panelFormSaveFailed);if(r.ok){ready=false;fields.disabled=true;}else{ready=false;groupsReady=false;}}catch{out.textContent=t.panelFormSaveFailed;ready=false;groupsReady=false;}finally{key.value='';summary();}};
window.Telegram?.WebApp?.ready();load();</script></body></html>`;
}
